---
# Globals
exclude: >
  ^(
    \.git/|
    magma-documentation/docs/|
    src/|
    \.idea/|
    \.vscode/
  )

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0  # Use the latest stable version
    hooks:
      - id: trailing-whitespace
        args: ["--markdown-linebreak-ext=md"]
        description: "Removes trailing whitespace"
      
      - id: end-of-file-fixer
        description: "Ensures files end with a newline"
      
      - id: check-added-large-files
        description: "Prevent large files from being added to the repo"
        args: ["--maxkb=500"]
        exclude: >
          ^(
            \.git/|
            magma-documentation/docs/|
            src/|
            \.idea/|
            \.vscode/
          )

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.35.1
    hooks:
      - id: yamllint
        description: "Lints YAML files"

  - repo: https://github.com/markdownlint/markdownlint
    rev: v0.13.0
    hooks:
      - id: markdownlint
        name: Markdownlint
        description: Run markdownlint on your Markdown files
        entry: mdl
        language: ruby
        files: \.(md|mdown|markdown)$
